### ISSUE TITLE
NodeSchool #5 in September

### ISSUE THREAD

**Issue by jpwesselink** [nodeschool/amsterdam#11]
- [x] :calendar: Agree on a date - September 1st
- [ ] :school: Post event on nodeschool.io
- [ ] :mortar_board: Mentor lineup
- [ ] :ramen: :tropical_drink: Food & drinks
- [ ] :speech_balloon: Post to Gitter channel 
- [ ] :octocat: Inform on GitHub
- [x] ⬢ Stickers 
- [x] :newspaper: Flyers
- [x] :scroll: Rollup banner
- [x] :bird: Tweet about the event
- [ ] :house: Update homepage
- [ ] :email: send attendee list to event host
- [ ] :alarm_clock: Send reminder to participants at the day of event
- [ ] :love_letter: Write a follow up mail

**Comment by watilde** [comment]
What can I help for this? I'm happy to join into it as a Mentor 😃

**Comment by jpwesselink** [comment]
Dear @watilde @JillesMe @leudanielm @mwoudenberg @CarmenPopoviciu, we'd love to have you as mentors :D

**Comment by watilde** [comment]
Yeah I'd love to be a mentor 😺

**Comment by leudanielm** [comment]
Count me in! 🍻

**Comment by jillesme** [comment]
I'm 100% in! 😁

**Comment by jillesme** [comment]
Don't you mean @mikewoudenberg ?

**Comment by jpwesselink** [comment]
@jillesme yes, @mikewoudenberg :)

**Comment by mikewoudenberg** [comment]
Hey count me in!

**Comment by mikewoudenberg** [comment]
Thanx for the namedrop @jillesme ! And @jpwesselink of course

**Comment by jpwesselink** [comment]
Really happy to get so much response so fast! 🙌

**Comment by jillesme** [comment]
Enthusiasm 👍

**Comment by CarmenPopoviciu** [comment]
Happy to...perhaps a good idea to join as a mentor for the second edition
in AMS?



--
with☺by
*Carmen Popoviciu*
*___________________*

(+31) 681 505 833
carmen.popoviciu@gmail.com
<https://twitter.com/CarmenPopoviciu>
<https://plus.google.com/u/0/118143942632321563925/posts>

**Comment by jpwesselink** [comment]
Let me create a ticket for that once I have a date. Aiming for t=0 +1M

**Comment by CarmenPopoviciu** [comment]
(thumbs up)



--
with☺by
*Carmen Popoviciu*
*___________________*

(+31) 681 505 833
carmen.popoviciu@gmail.com
<https://twitter.com/CarmenPopoviciu>
<https://plus.google.com/u/0/118143942632321563925/posts>
