### ISSUE TITLE
Create a logo

### ISSUE THREAD

**Issue by jpwesselink** [nodeschool/amsterdam#12]

**Comment by jpwesselink** [comment]
![nodeschool-amsterdam-shadow](https://cloud.githubusercontent.com/assets/1814479/13550250/ef17a8a8-e319-11e5-8f65-34d115a02d4b.png)

**Comment by watilde** [comment]
Cool :+1:

**Comment by jpwesselink** [comment]
Ty!

**Comment by yoshuawuyts** [comment]
hell yeah! :sparkles:

**Comment by jpwesselink** [comment]
Cleaner version: 
![nodeschool-amsterdam-shadow](https://cloud.githubusercontent.com/assets/1814479/13601318/705582ca-e52f-11e5-91fd-6e5276a27247.png)
