### ISSUE TITLE
Getting the show back on the road

### ISSUE THREAD

**Issue by jpwesselink** [nodeschool/amsterdam#13]
Hi all,

After a hiatus of almost 16 months, we’re happy to announce that NodeSchool Amsterdam will see some new life. In the last couple of weeks a new team of organizers has started working behind the scenes on planning new events.

Although we’re not ready to disclose the details just yet, we do want to share some of the outlines for NodeSchool Amsterdam with you.
- Our aim is to organize a NodeSchool event at least once a month, starting with the upcoming event that will take place within the next 6-8 weeks.
- NodeSchool is about teaching programming skills using JavaScript and Node.js through self-guided and hands-on workshops. Listening to someone talk code might be nice, but we want you to get your hands dirty by doing some coding yourself.
- We want the events to be interactive, social and, above all, fun. So during the events, we would love for you to get to know and collaborate with others.
- We encourage people to contribute. NodeSchool is an open-source initiative and we’d like others to get actively involved. So if you want to help out or just share your thoughts, get in touch with us on [GitHub Issues](https://github.com/nodeschool/amsterdam/issues/), [Gitter](https://gitter.im/nodeschool/amsterdam) or [Twitter](https://twitter.com/NodeSchoolAMS).
- Above all, NodeSchool welcomes everyone and we expect you to be kind to others and respect our [Code of Conduct](https://github.com/nodeschool/amsterdam/blob/master/code-of-conduct.md).

As stated above, we’re currently working very hard to get a new event organized and we’ll announce the date as soon as we can on GitHub Issues and [Meetup.com](http://www.meetup.com/nodeschool-amsterdam/). We’ll also be looking for mentors, so if you’d like to help us out, let us know.

Stay tuned!

**Comment by fruitl00p** [comment]
:+1:

**Comment by watilde** [comment]
Good news! Let me support it :smiley:

**Comment by rictorres** [comment]
:+1:
