### ISSUE TITLE
Create flyer design

### ISSUE THREAD

**Issue by jpwesselink** [nodeschool/amsterdam#17]
### front

![nodeschool-amsterdam-flyer-a5-tall-front](https://cloud.githubusercontent.com/assets/1814479/15540206/6fb41cac-2286-11e6-811b-a11440238db8.png)

### back

![nodeschool-amsterdam-flyer-a5-tall-back](https://cloud.githubusercontent.com/assets/1814479/15540205/6f9e1f56-2286-11e6-84a2-fafd9a8c00ed.png)

**Comment by JanGroot** [comment]
Nodeschool Haarlem is mentioned in front, should that be Ams? 

And offcourse kudos +1

**Comment by jpwesselink** [comment]
!!!

**Comment by jpwesselink** [comment]
Good catch! Fixed!
