### ISSUE TITLE
Mentors for June 9th

### ISSUE THREAD

**Issue by jpwesselink** [nodeschool/amsterdam#23]
- [x] @jpwesselink
- [x] @rickheere 
- [x] @stefanmirck 
- [ ] @lulusam
- [x] @watilde 
- [x] @yoshuawuyts

**Comment by watilde** [comment]
Yeah I'm in 😺

**Comment by yoshuawuyts** [comment]
Yaaaaaassssss!

**Comment by jpwesselink** [comment]
Since venue did not come through we skipped this, buuuuutttt we have a new date: July 7th

**Comment by lulusam** [comment]
wooop wooop 

that is big!!!
