### ISSUE TITLE
NodeSchool at Node.js Interactive

### ISSUE THREAD

**Issue by mikeal** [nodeschool/amsterdam#24]
Heya,

We have a room for workshops during Node.js Interactive. We've accepted a couple 1-hour workshops but we still have room for more and were thinking it would be cool to have NodeSchools take over the room during that time.

Thoughts?

**Comment by jpwesselink** [comment]
Awesome, how about we have a session on getting started with node: focus on installation and core workshoppers

**Comment by mikeal** [comment]
i would expect most interactive attendees to be past the basics, which could be a rare chance to dive into some of the more advanced workshoppers.

**Comment by jpwesselink** [comment]
That is a welcoming change : ) One hour might be a bit short, is time still available, or is it already scarce?

**Comment by jpwesselink** [comment]
As for workshoppers, what would be more suitable: `functional-javascript-workshop` or `node-debug-school`?

**Comment by mcollina** [comment]
I think we might go even with going-native, if we want something a bit harder.

**Comment by jpwesselink** [comment]
How about `learnuv`?

**Comment by mcollina** [comment]
I've never done that, but I think we can prepare it.

**Comment by jpwesselink** [comment]
@mcollina theee

**Comment by jpwesselink** [comment]
@mikeal Do you have an estimate on how many people will attend?
