### ISSUE TITLE
Workshoppers for Node.js Interactive

### ISSUE THREAD

**Issue by jpwesselink** [nodeschool/amsterdam#26]
Since we'll be doing two NodeSchool sessions at Node.js Interactive we should select two workshoppers which focus on more challenging aspects of JS and Node.js. As first contender I think https://github.com/mikaelbr/bacon-love is pretty awesome. 

What do you think might be a good second workshopper? 

cc @mikeal @mcollina @rickheere @stefanmirck @mikaelbr

**Comment by mikaelbr** [comment]
Something that is often overlooked, even by seasoned developers is understanding how the prototype object model actually works. That is especially true now a days when people often use abstractions or sugar, but it still is knowledge that is important, IMO.

I haven't tried this one out, but this one looks interesting: https://github.com/sporto/planetproto

Good luck with Node.js Interactive. It looks like an awesome event.

**Comment by leudanielm** [comment]
https://github.com/mikaelbr/bacon-love is awesome, indeed, but it is definitely an advanced topic. I might also add that it should probably emphasise a little more on the BaconJS documentation at first.
I enjoy it myself, great job with this workshopper :)

**Comment by mikaelbr** [comment]
@leudanielm Thank you very much. If you find any issues or think of any improvements at all (such as lacking docs or lacking info), contributions are very much welcome or just an [issue pointing it out](https://github.com/mikaelbr/bacon-love/issues/new). It's difficult for us who have worked on it to see if all points come across.

**Comment by jpwesselink** [comment]
Thanks @mikaelbr and @leudanielm. We'll give planetproto a try tonight at NodeSchool Haarlem, to see how well it works :D As for bacon-love, do you have time to merge pull requests coming week?

**Comment by mikaelbr** [comment]
Absolutely. We are several people who have access to merging.

**Comment by jpwesselink** [comment]
Cool. Would be nice to iron out any wrinkles :D

**Comment by mikaelbr** [comment]
That would be very nice the workshop as well 👍

**Comment by mcollina** [comment]
going native is usually a good choice. It explains the architecture of a C++ addon, and it does not require huge knowledge of C++.

**Comment by jpwesselink** [comment]
@mcollina does it still bear relevance?

**Comment by mcollina** [comment]
IMHO people do not ask themselves _"shoud I study how native addons works?"_, but it is a key differentiator in skills. I agree it is not a hot topic.

**Comment by leudanielm** [comment]
@mcollina @jpwesselink It really depends on what's the level of the attendants, but I think some hot topics would be ES6 / functional programming in JS. With this plethora of frameworks, people are just stuck in learning them and not the intricacies of the JS language. I think it would be a good opportunity for lots of people to get a better taste of JS and what's new in it (lots of people have no idea about ES6, or just have some theoretical knowledge about it). Just my 2 cents.

**Comment by jpwesselink** [comment]
@mcollina It might not be hot, but as long as it doesn't learn people the wrong things it is fine.

**Comment by mcollina** [comment]
I also agree that ES6 is a very hot topic. Something that shows how ES6 in node v6 can simplify the code.

**Comment by jpwesselink** [comment]
ES6 in Node, too bad this one uses Traceur:  https://github.com/domenic/count-to-6

**Comment by leudanielm** [comment]
But ES6 in node is almost fully supported right? I guess it uses traceur to check the output? Maybe there's something to be done with ESLint with some restrictions in the conf in order to make use of the ES6 syntax. Otherwise the unit test cannot know whether you have used ES6 or not in your solution.

**Comment by jpwesselink** [comment]
count-to-6 could use a lot more features, like classes and generators. Definitely a project to contribute to, but I don't think this workshopper is suitable for Node.js Interactive.

**Comment by jpwesselink** [comment]
You know, the more I learn about ES6 classes, the more I think it is necessary for people to understand prototypes since it defines what JS is.

**Comment by leudanielm** [comment]
Then maybe we should go back to what @mikaelbr suggested in the first place? https://github.com/sporto/planetproto

**Comment by jpwesselink** [comment]
Sounds like a plan. I think we will pair a hard workshopper with one more suitable for less experienced devs.

- planetproto + going-native
- stream-adventure + bacon-love

**Comment by martinheidegger** [comment]
- lololodash is in long need of an update but would be a very healthy material (if it was working, i think it is even broken atm.)
- bacon-love : It would be nice if someone updated it to the latest workshopper-adventure (should be short job)
- how-to-npm: Advanced people tend to learn something new with it and it is important for beginners

**Comment by jpwesselink** [comment]
Thanks all, I'm going to close this now :D
