### ISSUE TITLE
NodeSchool at Node.js Interactive mentors

### ISSUE THREAD

**Issue by jpwesselink** [nodeschool/amsterdam#27]
Dear mentors this is your captain speaking,

Time for our final call to get everybody on board of NodeSchool Airlines at Node.js Interactive.
![open up](https://metrouk2.files.wordpress.com/2015/03/plane.gif)

We will be doing _two_ sessions. As for the curriculum we will focus on paired workshoppers: an easy one and a not-so-easy one.
- 9:00am - 12:20pm  **stream-adventure + bacon-love**
- 1:40pm - 3:50pm **planet-proto + going-native**

Please let us know if can - or can't - make it, and we'll make sure you get in. (Plus an extra beer at _our_ amazing beer.js after-partée on Fri evening)
### morning session 9:00am - 12:20pm

[event page](https://eventmobi.com/nieu16/agenda/176233/997889)
- [x] @watilde
- [x] @rickheere 
- [x] @stefanmirck 
- [x] @leudanielm
- [x] @jpwesselink
- [x] @lulusam
- [x] @mcollina 
- [x] @wooorm
- [ ] @yoshuawuyts 
- [ ] ~~@CarmenPopoviciu~~
- [ ] ?
- [ ] ?
### afternoon session 1:40pm - 3:50pm

[event page](https://eventmobi.com/nieu16/agenda/176233/997891)
- [x] @watilde
- [x] @rickheere 
- [x] @stefanmirck 
- [x] @leudanielm
- [x] @jpwesselink
- [x] @lulusam
- [x] @wooorm
- [x] @lucamaraschi
- [ ] @yoshuawuyts
- [ ] ~~@mcollina~~
- [ ] ~~@CarmenPopoviciu~~
- [ ] ?
- [ ] ?

**Comment by wooorm** [comment]
I’ll be there at both sessions, could someone check my boxes? ❤️

**Comment by leudanielm** [comment]
It's an honour guys! See you at the event!

**Comment by CarmenPopoviciu** [comment]
I won't be able to, even though I want super much. I am very sorry :(



--
with☺by
*Carmen Popoviciu*
*___________________*

(+31) 681 505 833
carmen.popoviciu@gmail.com
<https://twitter.com/CarmenPopoviciu>
<https://plus.google.com/u/0/118143942632321563925/posts>

**Comment by mcollina** [comment]
cc @lucamaraschi @mcdonnelldean

**Comment by lucamaraschi** [comment]
I am in! ;-)

**Comment by mcdonnelldean** [comment]
I can give an hour at least. Maybe more with depending. I'm in!

Kindest Regards,

Dean

On 13 Sep 2016, at 12:59, Luca Maraschi <notifications@github.com<mailto:notifications@github.com>> wrote:


I am in! ;-)

-

**Comment by jpwesselink** [comment]
Thanks @mcollina, @lucamaraschi and @mcdonnelldean! 

@mcdonnelldean Which session would be best for you?

**Comment by stefanmirck** [comment]
Hi mentors,

Firstly a big thank you for being epic and volunteering as a mentor. We love you! <333

With this email we would like to give you some info about what to expect tomorrow (Friday 16th Sep.) before, during and after the NodeSchool sessions during Node.js Interactive Europe.

Please note that a mentor's briefing will take place in before the start of each session. During the briefing we will go more in depth on how the sessions will be set up and will coordinate the mentor powers.

### Agenda: 
8:30AM – 9:00AM Mentors' briefing morning session
9:00AM – 12:20PM: Morning session (workshoppers covered: `stream-adventures` and `bacon-love`) 
1:10PM – 1:40PM: Mentor's briefing afternoon session
1:40PM – 3:50PM: Afternoon session (workshoppers covered: `going-native`, `planetproto`)

6:30PM – late: Join us for Beer.js (more info available at: http://nodeschool.io/amsterdam/nodejs-interactive-europe-2016-beerjs-at-hoppy-days/)
