### ISSUE TITLE
Beer.js?

### ISSUE THREAD

**Issue by 0x00A** [nodeschool/amsterdam#30]
Hey lovely Amsterdam Javascripters, when is the next beer.js? Also, I'm doing a **FREE** event. It's on the subject of reverse engineering with nodejs and radare (there will also be beer) details are here -- [https://fullstacklab.eu/](https://fullstacklab.eu/).

**Comment by jpwesselink** [comment]
*FREE* as in *BEER*. We have no beer.js planned right now. I'd like to come over on the 17th to see  how you teach, is it ok to attend and have a chat?

**Comment by 0x00A** [comment]
@jpwesselink of course! All are welcome 💯

**Comment by jpwesselink** [comment]
Wrong date display on https://fullstacklab.eu/radare/ ?


<img width="203" alt="screen shot 2016-10-11 at 11 33 20" src="https://cloud.githubusercontent.com/assets/1814479/19265730/941752e8-8fa6-11e6-98b9-78799a41793a.png">

**Comment by 0x00A** [comment]
That should be fixed, it was a typo on the home page.

![image](https://cloud.githubusercontent.com/assets/136109/19265839/4853c8b8-8fa7-11e6-8e25-81b1f631e2f8.png)

**Comment by jpwesselink** [comment]
Clicking the top register button opens a modal, clicking the bottom register button only changes the button text to 'loading...'. 

![screen shot 2016-10-11 at 11 47 47](https://cloud.githubusercontent.com/assets/1814479/19266176/9a222012-8fa8-11e6-8ba0-1dfe4d9942eb.png)

**Comment by 0x00A** [comment]
We were trying out https://ti.to for events. But I think it's not really able to handle events that aren't yet live? (we're just making them all live now so they dont do that). /cc @paulca

**Comment by jpwesselink** [comment]
Hope that fixes it, if you want me to test just let me know

**Comment by paulca** [comment]
@0x00A The default state for a new event is "draft", and live basically means "published and accessible" ... so setting them all to live would definitely be the thing to do!
