### ISSUE TITLE
Meetup #8 on ~Thursday~ Friday February the 3rd of 2017

### ISSUE THREAD

**Issue by jpwesselink** [nodeschool/amsterdam#33]
- [x] :house: Arrange event host
- [x] :school: Post event on nodeschool.io
- [x] :mortar_board: Mentor lineup
- [x] :ramen: :tropical_drink: Food & drinks
- [ ] :speech_balloon: Post to Gitter channel 
- [x] :octocat: Inform on GitHub
- [x] :bird: Tweet about the event
- [ ] :email: send attendee list to event host
- [ ] :alarm_clock: Send reminder to participants at the day of event
- [ ] :love_letter: Write a follow up mail

Mentors

- [x] @watilde 
- [x] @rickheere 
- [x] @stefanmirck 
- [x] @jpwesselink
- [x] @RamonGebben
- [ ] @lulusam
- [ ] ~@mikewoudenberg 😢~
- [x] @skwakman
- [x] @traumverloren
- [ ] @wietsevenema
- [ ] you?
- [ ] you?
- [ ] you?

**Comment by jpwesselink** [comment]
Mentooooorrsss @watilde @lulusam @mikewoudenberg @skwakman @traumverloren @wietsevenema! :D :D :D

**Comment by watilde** [comment]
I will 🙋‍♂️

**Comment by skwakman** [comment]
yeah I can be there. Looking at the topics there's a good chance I'll be learning a lot as well :)

**Comment by traumverloren** [comment]
Sure thing. 🙃

**Comment by RamonGebben** [comment]
I'm ok to mentor :)

**Comment by mikewoudenberg** [comment]
Sorry people... Not this time :crying_cat_face:

**Comment by jpwesselink** [comment]
@mikewoudenberg https://www.meetup.com/beerjs-amsterdam/events/237320327/

**Comment by jpwesselink** [comment]
Dear all, I fubarred the day: it is held on Friday, not on Thursday!
