### ISSUE TITLE
Planning 2017

### ISSUE THREAD

**Issue by jpwesselink** [nodeschool/amsterdam#36]
Here is a planning for this year, this includes Haarlem as well. 

## Predictability is great

| Chapter   | Day | Frequency | 
| --------- | --- | --------- |
| Amsterdam | First Friday of the month | Monthly | 
| Haarlem   | Second/third Friday of the month | Monthly | 

## Year planning

| Month | Amsterdam | Haarlem  | 
| ----- | --------- | -------- |
| Feb   | Fri 3rd   | Fri 10th |
| Mar   | Fri 3rd   | Fri 10th | 
| Apr   | Fri 7th   | Fri 14th | 
| May   | Fri 5th   | Fri 12th | 
| Jun   | Fri 2nd   | Fri 9th  | 
| Jul   | Fri 7th   | Fri 21th |
| Aug   | ~~Fri 4th~~   | Fri 11th(??) |
| Sep   | Fri 1st   | Fri 8th  |
| Oct   | Fri 6th   | Fri 13th |
| Nov   | Fri 3rd   | Fri 10th |
| Dec   | Fri 1st   | Fri 8th  |

## Distribution of meetups

Since we're allocating the first and second Friday of the month, we don't really spread out our meetups. Should we do Haarlem on the third Friday?

**Comment by jpwesselink** [comment]
Also, since Anthony of KLM is hosting on Thursday the 9th of February at Schiphol, would it even be worth it to do Haarlem that week? I'm also good for moving to the 3rd week.

**Comment by jpwesselink** [comment]
@wooorm 👋 : ) Would the HvA still be interested in hosting?

**Comment by wooorm** [comment]
Yes, We can make it work. If it's not a Friday the building will stay open 'till 10 (I forgot about that), so it's definitely possible! Let me check which dates are most suited, BRB.

**Comment by wooorm** [comment]
There’s two courses in the minor (which that starts next week and lasts a semester) that fit well with NodeSchool. *Performance*, from 13 to 31 March (I’m thinking browserify-adventure, perfschool), and *real-time*, from 10 April to 5 May, which has to do with sockets. Both courses last three weeks, and the last week is rather busy with deliverables and stuff. The weeks before/between/after them are each a project week (a.k.a. very busy).

I think it’d be cool to connect this minor with NodeSchool, but unfortunately the dates don‘t match up. How flexible are the NodeSchool AMS dates? For example, would it be possible for HvA to host NodeSchool in April, but a week later, on Thursday (April 13)?

**Comment by stefanmirck** [comment]
I updated the schedule.

We still need to agree with @artorozenga if Haarlem will be organized on the second or third Friday of the month.
