### ISSUE TITLE
Helping Out!

### ISSUE THREAD

**Issue by AlexTes** [nodeschool/amsterdam#39]
Hi @jpwesselink!

We met, we talked, nodeschool is amazing, and I'd like to help out!

**Comment by jpwesselink** [comment]
👋 Welcome! Want to mentor?

**Comment by AlexTes** [comment]
Yes! I very much do. Just joined all the NodeSchool groups here in The Netherlands, I'll be showing up to every Amsterdam NodeSchool meet up if they are all as fun as the last! I'll likely be helping people at them too, as I did last week because I find that great fun.

So yes, I'd love to mentor.

**Comment by jpwesselink** [comment]
Seems you will be mentoring, great! Let's close this!
