### ISSUE TITLE
Meetup #9 Friday, March 3, 2017 Mentor call!

### ISSUE THREAD

**Issue by jpwesselink** [nodeschool/amsterdam#41]
Dear mentors, for our next instalment of NodeSchool Amsterdam we'd like to invite you to mentor with us! 

- [x] @jpwesselink
- [x] @stefanmirck 
- [x] @rickheere 
- [x] @mikewoudenberg 
- [x] @lulusam
- [x] @AlexTes
- [x] @leudanielm 
- [x] @skwakman 
- [x] @addaleax
- [x] @codeflyer
- [x] @traumverloren
- [x] @watilde  

@AlexTes @skwakman @mikewoudenberg @lulusam @RamonGebben @traumverloren @wietsevenema @jillesme @watilde also @wooorm, @leudanielm, @fritzvd, @CarmenPopoviciu

**Comment by mikewoudenberg** [comment]
`count(meIn);`

**Comment by lulusam** [comment]
I'm in :)

**Comment by alextes** [comment]
🙋 in. Yaaaaay!

**Comment by monostere0** [comment]
Count me in! 👍

**Comment by skwakman** [comment]
I'll probably have to leave a bit early, but I'll be there!

**Comment by addaleax** [comment]
o/ Me too!

**Comment by alextes** [comment]
@addaleax That's awesome! How many secret node legends does the node amsterdam community count?! Core contributor 16 no less. Looking forward to it even more now 🙌 .

**Comment by jpwesselink** [comment]
@addaleax awesome you can come!

**Comment by codeflyer** [comment]
I'm there as well!!

**Comment by jpwesselink** [comment]
Oh and btw, let's have drinks as well afterwards! 

Wow such beer, much social wow
http://meetu.ps/e/CrPnr/t4Dpr/a

**Comment by traumverloren** [comment]
i'll be there, of course.

**Comment by watilde** [comment]
🙋‍♂️

**Comment by jpwesselink** [comment]
Does anyone need directions?

**Comment by jpwesselink** [comment]
If so, take a peek here: http://meetu.ps/e/CrPPk/t4Dpr/a
