### ISSUE TITLE
Meetup #10 Friday, April 7, 2017 Mentor call!

### ISSUE THREAD

**Issue by jpwesselink** [nodeschool/amsterdam#44]
Dear mentors, guess what time it is..... Awwww yisssss NodeSchool Tiiiiime! Who wants to come mentor with us? 

- [ ] You?
- [ ] You?
- [ ] You?
- [ ] You?
- [ ] You?
- [x] @traumverloren
- [x] @leudanielm
- [x] @wooorm 
- [x] @jpwesselink
- [x] @stefanmirck 
- [x] @rickheere 
- [x] @lulusam
- [x] @AlexTes

@AlexTes @skwakman @mikewoudenberg @lulusam @RamonGebben @traumverloren @wietsevenema @jillesme @watilde also @wooorm, @leudanielm, @fritzvd, @CarmenPopoviciu

**Comment by alextes** [comment]
Check that box! ✔️🙌

**Comment by wooorm** [comment]
Yes!

**Comment by lulusam** [comment]
I'm in too!

**Comment by rickheere** [comment]
As always :D

**Comment by mikewoudenberg** [comment]
Not in :( Sorry

**Comment by jillesme** [comment]
Sorry guys, I don't live in the Netherlands anymore!

**Comment by stefanmirck** [comment]
Too bad @mikewoudenberg. Maybe next time?

@jillesme: you’re always welcome whenever you’re back in the Low Countries.
