### ISSUE TITLE
Mentor call workshop #11 Friyay, May 12 2017

### ISSUE THREAD

**Issue by stefanmirck** [nodeschool/amsterdam#46]
Dear mentors, it’s that time again and we want to call on you to help us out. Who’s with us?

- [x] @rickheere 
- [x] @stefanmirck
- [x] @leudanielm 
- [x] @traumverloren
- [x] @wooorm 
- [x] @auremoser
- [ ] @skwakman 
- [x] @AlexTes 
- [x] @joeyklee 
- [ ] you?
- [ ] you?
- [ ] you?

@AlexTes @skwakman @mikewoudenberg @lulusam @RamonGebben @traumverloren @wietsevenema @watilde @wooorm @leudanielm @fritzvd @CarmenPopoviciu @pverbeek

**Comment by monostere0** [comment]
Count me in, dude!

**Comment by traumverloren** [comment]
I can help. 

I've also recruited a visiting dev to check out Nodeschool AMS while she's here! (Aurelia Moser)

**Comment by wooorm** [comment]
Yup, I’ll be there!

**Comment by stefanmirck** [comment]
@traumverloren: have you recruited Aurelia as a mentor? If so, I’ll add her to the list.

**Comment by wooorm** [comment]
cc @auremoser

**Comment by auremoser** [comment]
Oh dope. Yep yup, sure, happy to help. What does this involve?

**Comment by skwakman** [comment]
I'm there!

**Comment by traumverloren** [comment]
@auremoser eating pizza, drinking beer (or other non-beer beverages), and helping out anyone that has questions about the nodeschool workshoppers. 😃

**Comment by traumverloren** [comment]
it's pretty chill

**Comment by alextes** [comment]
Wouldn't miss it 😁! See you all soon.

**Comment by auremoser** [comment]
Oh also @joeyklee, are you into this? Come hang out.

**Comment by joeyklee** [comment]
Oh hello everyone 🤗 - I'd be happy to join the fun, if there's space for a +1. thanks for the invite @auremoser

**Comment by auremoser** [comment]
well-played with that rhyme you made, @joeyklee

**Comment by stefanmirck** [comment]
@joeyklee: great you want to join! I’ll add you as a mentor!

@auremoser and @joeyklee: you can also checkout the [Meetup.com page for the event](https://www.meetup.com/nl-NL/nodeschool-amsterdam/events/237321545/), so you have the address of the venue.

**Comment by skwakman** [comment]
Very very sorry but I cannot make it tomorrow. I hope you have enough mentors!

**Comment by stefanmirck** [comment]
@skwakman: too bad, but I think we can manage. Hope to see you soon!

**Comment by stefanmirck** [comment]
@traumverloren, @auremoser, @joeyklee, @leudanielm, @wooorm, @AlexTes and @rickheere:

I just sent out a reminder of tomorrow’s workshop thru Meetup. As doors open at 18:30 for participants, I want to ask you if you could be at info.nl around 18:00 to help me out a bit with setting up.

If you’re at the door, just ring the bell and drop my name.

**Comment by rickheere** [comment]
I'll be there

**Comment by monostere0** [comment]
Me too!

**Comment by watilde** [comment]
Oh sorry I couldn't make it for this time ;(
Hope you all will enjoy it!

**Comment by mikewoudenberg** [comment]
Whoa, just found this. Won't be able to make it :(

**Comment by stefanmirck** [comment]
@watilde, @mikewoudenberg: too bad you can’t make it. But we still love you. See you soon!

**Comment by traumverloren** [comment]
@stefanmirck I'll try to get there earlier if I can....

**Comment by stefanmirck** [comment]
@traumverloren, @auremoser, @joeyklee, @AlexTes, @wooorm, @leudanielm and @rickheere: thanks for mentoring and helping me with setting up before  the workshop and cleaning up afterwards. I really appreciate it! Hugs!

— S.
