### ISSUE TITLE
Mentor call workshop #12 Friday, 2 June 2017

### ISSUE THREAD

**Issue by stefanmirck** [nodeschool/amsterdam#48]
Dear mentors, we want to call upon you to help us out again. Are you with us?

- [x] @jpwesselink 
- [x] @rickheere
- [x] @stefanmirck
- [x] @traumverloren 
- [x] @AlexTes 
- [x] @wooorm 
- [x] @leudanielm 
- [ ] you?
- [ ] you?
- [ ] you?
- [ ] you?
- [ ] you?

@AlexTes @skwakman @mikewoudenberg @lulusam @RamonGebben @traumverloren @wietsevenema @watilde @wooorm @leudanielm @fritzvd @CarmenPopoviciu @pverbeek

**Comment by traumverloren** [comment]
I'm in ✔️

**Comment by alextes** [comment]
🙋‍♂️

**Comment by mikewoudenberg** [comment]
Out again :( sorry...

**Comment by wooorm** [comment]
I’ll be there!

**Comment by monostere0** [comment]
I'm in!

**Comment by jayne-mast** [comment]
I'll be there, but won't be mentoring. Might be better if I actually attend one first ;-)

**Comment by skwakman** [comment]
Sadly I can't be there, sorry!
