### ISSUE TITLE
Mentor call workshop #13 Friday, 7 July 2017

### ISSUE THREAD

**Issue by stefanmirck** [nodeschool/amsterdam#49]
Dear mentors, we need some extra hands for the next workshop. Will you help us out?

 - [x] @jpwesselink
 - [x] @rickheere
 - [x] @stefanmirck
 - [x] @wooorm 
 - [x] @watilde 
 - [x] @RamonGebben 
 - [ ] you?
 - [ ] you?
 - [ ] you?
 - [ ] you?

@AlexTes @skwakman @mikewoudenberg @lulusam @RamonGebben @traumverloren @wietsevenema @watilde @wooorm @leudanielm @fritzvd @CarmenPopoviciu @pverbeek

**Comment by wooorm** [comment]
Yup!

**Comment by watilde** [comment]
o/ yes

**Comment by traumverloren** [comment]
yassss

(of course)

**Comment by traumverloren** [comment]
🤔 maybe @0x00A would like to hang out & mentor?

**Comment by stefanmirck** [comment]
@AlexTes, @watilde: I saw on Meetup.com that you’re attending. Can I add you to the list?

**Comment by traumverloren** [comment]
@stefanmirck: ^^^ @watilde already commented & is on the list above... ? 🤔

**Comment by stefanmirck** [comment]
@traumverloren: Geez… I completely missed it, though I added @watilde to the list myself. Wut?! 😵

**Comment by RamonGebben** [comment]
Count me in!

**Comment by alextes** [comment]
I'll be on a 3-day company trip so I can't make it to this one 😭. I will sorely miss all of you 👨‍👨‍👧‍👦 !
(Updated my meetup status too)

**Comment by traumverloren** [comment]
@stefanmirck Stefan, sorry, I'm going to miss this one after all.

**Comment by skwakman** [comment]
Sorry, cant make this one. Have fun!

**Comment by stefanmirck** [comment]
@traumverloren, @AlexTes, @skwakman: too bad you can’t make it. 😢 Next time tho!
