### ISSUE TITLE
Mentor call workshop #14 Friday, 1 September 2017

### ISSUE THREAD

**Issue by stefanmirck** [nodeschool/amsterdam#51]
Summer break is over, school’s back in and so we are in need of mentors for NodeSchool. Will you help us out again?

 - [x] @jpwesselink
 - [x] @rickheere
 - [x] @stefanmirck
 - [x] @mikewoudenberg 
 - [x] @GeorgeSapkin 
 - [ ] you?
 - [ ] you?
 - [ ] you?
 - [ ] you?
 - [ ] you?

@AlexTes @skwakman @mikewoudenberg @lulusam @RamonGebben @traumverloren @wietsevenema @watilde @wooorm @leudanielm @fritzvd @CarmenPopoviciu @pverbeek

**Comment by wooorm** [comment]
Unfortunately I can’t! ☹️

**Comment by alextes** [comment]
Might be at a conference 😞 . Will update once I know more.

**Comment by mikewoudenberg** [comment]
Count me in!

**Comment by GeorgeSapkin** [comment]
I'll be there as well.

**Comment by skwakman** [comment]
Sorry, can't make it :(

**Comment by stefanmirck** [comment]
@wooorm, @AlexTes, @skwakman: too bad you can’t make it. Was hoping to see you again. But you’re always welcome to join us next time! ❤️

**Comment by traumverloren** [comment]
@stefanmirck sorry, won't be there.

**Comment by stefanmirck** [comment]
@traumverloren: darn! Hope to see you soon again tho!
