### ISSUE TITLE
Mentor call workshop the WWWTF edition, Friday, October 6

### ISSUE THREAD

**Issue by stefanmirck** [nodeschool/amsterdam#52]
Next month we’re doing a special What The Fest edition of NodeSchool Amsterdam. Who wants to help us out?

 - [x] @jpwesselink
 - [x] @rickheere
 - [x] @stefanmirck
 - [x] @wooorm 
 - [x] @GeorgeSapkin 
 - [x] @AlexTes 
 - [x] @AnneKlapwijk
 - [ ] you?
 - [ ] you?
 - [ ] you?

@AlexTes @skwakman @mikewoudenberg @lulusam @RamonGebben @traumverloren @wietsevenema @watilde @wooorm @leudanielm @fritzvd @CarmenPopoviciu @pverbeek

**Comment by watilde** [comment]
Can't join because of `Node.js Interactive 2017` ;(
next time!

**Comment by wooorm** [comment]
Check! ✅

**Comment by jayne-mast** [comment]
Can't join because of Fronteers

**Comment by traumverloren** [comment]
I cannot.

**Comment by GeorgeSapkin** [comment]
I'll be there as well.

**Comment by alextes** [comment]
🙋 🙌 
I can make it this time!
![omgiwon](https://user-images.githubusercontent.com/2011351/31215759-133f136a-a9b1-11e7-9160-c6d3836c6e7b.gif)

**Comment by traumverloren** [comment]
@stefanmirck can I be taken off the mentor list? I will not be mentoring or attending in the foreseeable future. Thank you.
