### ISSUE TITLE
Mentor call for Friday, November 3, 2017

### ISSUE THREAD

**Issue by stefanmirck** [nodeschool/amsterdam#54]
Just announced our next workshop, so once again we’re looking for mentors help us out. Who wants to join us? (Also, it’s my birfday, so mebbe I’ll bring something sweet for y’alls to eat.)

 - [x] @jpwesselink
 - [x] @rickheere
 - [x] @stefanmirck
 - [x] @AnneKlapwijk 
 - [x] @GeorgeSapkin 
 - [x] @AlexTes 
 - [x] @watilde 
 - [ ] you?
 - [ ] you?
 - [ ] you?

@AlexTes @skwakman @mikewoudenberg @lulusam @RamonGebben @wietsevenema @watilde @wooorm @leudanielm @fritzvd @CarmenPopoviciu @GeorgeSapkin @AnneKlapwijk @toddmerrill

**Comment by wooorm** [comment]
Can’t unfortunately! 😢

**Comment by AnneKlapwijk** [comment]
I'll be there

**Comment by stefanmirck** [comment]
@wooorm: too bad you can’t be there. Next time!

@AnneKlapwijk: ty! I’ve added you to the list! 😊

**Comment by GeorgeSapkin** [comment]
Count me in.

**Comment by stefanmirck** [comment]
Added!

**Comment by alextes** [comment]
NodeSchool on my birthday?
Let's do it 🎉 !
![iseeyou](https://user-images.githubusercontent.com/2011351/31943499-400cd6c6-b8c9-11e7-9d65-e6280c1f90f1.gif)

My attendance is a little tentative. I might have impromptu plans to run off to 😁 .

**Comment by watilde** [comment]
o/ I will make it

**Comment by stefanmirck** [comment]
@AlexTes, @watilde: sorry for the late reply, just started on a new project, but I added you to the list. See you tonight!
