### ISSUE TITLE
Mentor call for Friday, December 1, 2017 

### ISSUE THREAD

**Issue by AnneKlapwijk** [nodeschool/amsterdam#55]
Dear mentors, as always we need some help for our next workshop: [NodeSchool Amsterdam #17](https://www.meetup.com/nodeschool-amsterdam/events/245129686/). Who’s with us?

- [x] @stefanmirck
- [x] @rickheere
- [x] @jpwesselink
- [x] @AnneKlapwijk
- [x] @toddmerrill
- [x] @AlexTes
- [x] @daanpeer
- [ ] You?
- [ ] You?
- [ ] You?

@AlexTes @skwakman @mikewoudenberg @lulusam @RamonGebben @wietsevenema @watilde @wooorm @leudanielm @fritzvd @CarmenPopoviciu @GeorgeSapkin @AnneKlapwijk @toddmerrill @daanpeer

**Comment by RamonGebben** [comment]
Sadly I'm otherwise occupied that evening.

**Comment by alextes** [comment]
💪 👍

**Comment by AnneKlapwijk** [comment]
@AlexTes I've added you to the list 😊
See you tomorrow!
