### ISSUE TITLE
Mentor call for Friday, January 5, 2018

### ISSUE THREAD

**Issue by AnneKlapwijk** [nodeschool/amsterdam#56]
👋 Dear mentors, here's a new year's resolution idea: mentor at the first [NodeSchool](https://www.meetup.com/nodeschool-amsterdam/events/246072016/) of the year in Amsterdam! Are you with us?

- [x] @stefanmirck
- [x] @rickheere
- [x] @jpwesselink
- [x] @AnneKlapwijk
- [x] @AlexTes
- [x] You?
- [ ] You?
- [ ] You?
- [ ] You?
- [ ] You?

@AlexTes @skwakman @mikewoudenberg @lulusam @RamonGebben @wietsevenema @watilde @wooorm @leudanielm @fritzvd @CarmenPopoviciu @GeorgeSapkin @AnneKlapwijk @toddmerrill @daanpeer

**Comment by mikewoudenberg** [comment]
Sorry, have to disappoint you once again :(

**Comment by alextes** [comment]
Gotta be helpful to all those young JavaScript curious souls 🤗 !

![showmewhatyougot](https://user-images.githubusercontent.com/2011351/34248376-1eeb9550-e636-11e7-90d2-6f0674ce97b9.gif)

**Comment by AnneKlapwijk** [comment]
@mikewoudenberg Too bad, hope to see you next time!
