### ISSUE TITLE
Mentor call for Friday, Febuary 2, 2018

### ISSUE THREAD

**Issue by stefanmirck** [nodeschool/amsterdam#57]
Hi mentors 👋,

Hope you’re off to a great start of the new year? We’re already set thing in motion for the [second workshop](https://www.meetup.com/nodeschool-amsterdam/events/246875171/), but as always we can use some help! Are you with us?

- [x] @stefanmirck
- [x] @rickheere
- [x] @jpwesselink
- [x] @AnneKlapwijk
- [x] @alextes 
- [ ] You?
- [ ] You?
- [ ] You?
- [ ] You?
- [ ] You?

@AlexTes @skwakman @mikewoudenberg @lulusam @RamonGebben @wietsevenema @watilde @wooorm @leudanielm @fritzvd @CarmenPopoviciu @GeorgeSapkin @toddmerrill @daanpeer

**Comment by wooorm** [comment]
I can’t again 😢

**Comment by stefanmirck** [comment]
Too bad @wooorm. Hope to see you again soon!

**Comment by alextes** [comment]
Maybe we can make it an opt-out thing for me 😛. Coming 😁!

**Comment by stefanmirck** [comment]
@alextes: 😆. I’ve added you to the list!
