### ISSUE TITLE
Mentor call for NodeSchool # 21, Friday, April 6

### ISSUE THREAD

**Issue by stefanmirck** [nodeschool/amsterdam#59]
Hi mentors 👋,

Again, we’re calling upon you to help us out during the upcoming workshop. Please let us know if you’re available to mentor. We’re counting on you! 💖

- [x] @stefanmirck
- [x] @rickheere
- [x] @jpwesselink
- [x] @AnneKlapwijk
- [x] @alextes 
- [ ] You?
- [ ] You?
- [ ] You?
- [ ] You?
- [ ] You?

@skwakman @mikewoudenberg @lulusam @RamonGebben @wietsevenema @watilde @wooorm @leudanielm @fritzvd @CarmenPopoviciu @GeorgeSapkin @toddmerrill @daanpeer

**Comment by GeorgeSapkin** [comment]
I'm coming as well.

**Comment by monostere0** [comment]
Count me in!

**Comment by watilde** [comment]
I moved back to Japan already so cannot join anymore ;( It was fun tho! Hope I can come again.

**Comment by stefanmirck** [comment]
@leudanielm: didn’t see your response in time, so I didn’t add you to the slides, but it was great seeing you again! If you’re up for mentoring next time, lemme know!

@watilde: wishing you all the best back in Japan. If you’re visiting and it so happens that we’re organizing an event, you’re always more than welcome to join us! Take care my friend!
