### ISSUE TITLE
International Nodeschool Day on May 23rd!

### ISSUE THREAD

**Issue by yoshuawuyts** [nodeschool/amsterdam#6]
So [International Nodeschool Day][ind] is coming up! I was thinking of rounding up mentors before deciding on a location and topic. So feel invite anyone that might be interested in helping out! I was thinking of asking the UvA nicely if we could borrow some of their classrooms (maybe get students to come) for the day. Maybe even get ~100 people in, we'd need to have the man power to support it.

Anyway, this is the stuff I think should be done:
- [x] create this issue
- [ ] round up as many (qualified, skillful and handsome) mentors as possible
- [x] create a placeholder event on Meetup
- [ ] arrange a location
- [ ] decide on the overarching theme (introductory? specific topic? diverse? poll?)
- [ ] once a location & topic are decided, fill in the rest of the meetup details
- [ ] find sponsors for beer & pizza (essential in covering up any mistakes we make during the day)
- [ ] prepare the nodeschool workshops (it's more fun when you're prepared!)
- [ ] buzz people to come
- [ ] send a reminder a week before the meetup
- [ ] send a reminder a day before the meetup

cc/ @hughsk @ebabel @hatchan @3rd-Eden

Let me know if you guys can help out. Thanks!

## links 
- [international nodeschool day][ind]
- [meetup/nodeschool-amsterdam](http://www.meetup.com/nodeschool-amsterdam/)

[ind]: http://nodeschool.io/international-day/

**Comment by 3rd-Eden** [comment]
cc @swaagie

**Comment by Swaagie** [comment]
:+1: nice initiative :)

**Comment by yoshuawuyts** [comment]
Just created the meetup event. No details are disclosed yet, since we don't have anything to share at this point. The meetup invite asks people what workshops they want to take, so hopefully we'll get some data to base our selection of workshops on. We also have an option for a location that can hold ~50 ish people, but it's not confirmed yet (and not sure if it's suitable, so will have to check it out).

@Swaagie @3rd-Eden Can I interest you guys to be a mentor? In order to pull this event off we need a solid amount of experienced developers, and if you guys would be willing to assist that would be fantastic!

**Comment by Swaagie** [comment]
@yoshuawuyts we discussed and you can count us both in :)

**Comment by yoshuawuyts** [comment]
@Swaagie @3rd-Eden :tada: That's great! :D

**Comment by Swaagie** [comment]
@yoshuawuyts bad news, just got word from our employer (GoDaddy) that the 21-23rd is scheduled for an internal conference called techfest 2015, and we are expected to do a nodeschool like event on the 23rd. I'm sorry but you'll have to count us out for mentoring. We won't be back in the Netherlands until the 24th.

**Comment by yoshuawuyts** [comment]
@Swaagie Aw shucks, though no worries! Techfest sounds really nice though, hope you guys have fun there! Maybe see you guys another time! (:

**Comment by yoshuawuyts** [comment]
Oof, I haven't had the time do any further preparations. I'll be in SF for all of Aprils, so unless there we suddenly are able to get more mentors + a location I'm afraid we'll have to cancel.

**Comment by yoshuawuyts** [comment]
Cancelled the meetup a few weeks ago, closing this issue accordingly.
