### ISSUE TITLE
Mentor call! 👋 NodeSchool # 23, Thursday, February 29, 2024

### ISSUE THREAD

**Issue by AnneKlapwijk** [nodeschool/amsterdam#60]
Dear mentors,

Next month we’re doing a special throwback edition ™️  of NodeSchool Amsterdam 🥳 . 
Who wants to help us out and come mentor with us? 🙏💖

- [x] @stefanmirck
- [x] @jpwesselink
- [x] @AnneKlapwijk
- [x] @alextes
- [x] @CarmenPopoviciu
- [x] @TheMerski
- [ ] You?
- [ ] You?
- [ ] You?
- [ ] You?

 @alextes @RamonGebben @wooorm @fritzvd @CarmenPopoviciu @GeorgeSapkin @toddmerrill @daanpeer @lulusam

https://www.meetup.com/nodeschool-amsterdam/events/298328846

Edit: changed the start time of the event, but for mentors the doors are still open from 5:30 pm 🤗 
Looking forward to catch up with everyone!

**Comment by alextes** [comment]
I'm down. I have something in the calendar already but think I'll make it.

Made me smile to get the notification for this one 😄 .

**Comment by CarmenPopoviciu** [comment]
I'm down as well! 🤗
